version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - dev
      - test
      - prod

volumes:
  pgdata: